name: hypee
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.0.2
  google_fonts: ^6.2.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/brand/
    - assets/images/
    - assets/icons/
