name: hypee
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  dio: ^5.4.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.0.2
  google_fonts: ^6.2.0
  google_nav_bar: ^5.0.6
  icons_plus: ^5.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.0
  salomon_bottom_bar: ^3.3.2
  url_launcher: ^6.2.6

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint: ^2.1.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/brand/
    - assets/images/
    - assets/icons/
    - assets/lottie/
